### ISSUE TITLE
Upgrade to php8 failed

### ISSUE THREAD

**Issue by rstemmer** [anuko/timetracker#106]
Hi,

Since [Arch Linux switched to php8 as default PHP version](https://archlinux.org/news/php-80-and-php-7-legacy-packages-are-available/) I'd like to know when a Time Track version gets released that works with php8?

It was one of the applications that did not work with php8 - I'm using version 1.19.20.5234

kind regards
Ralf

**Comment by anuko** [comment]
Hi. Just wondering what specific things are broken with php8 apart from a flood of messages in error log that it introduces. I can try to reduce this flood partially. Problem is we use 3rd party librarires that do this too, so things are not easy to fix.

However, if something is broken apart from the error log problem please do let us know what it is exactly for further investigation. I suggest trying the latest Time Tracker bacsue some of the warnings were addressed lately.

**Comment by anuko** [comment]
I eliminated many php8 warnings so far, but many still remain. So far, I found and fixed only one minor issue with php8 which was related to attachments (with the attachments plugin enabled). Since the code base is large and php8 introduced a major headache with error log flooding, I am closing this issue for now because, at this time, we don't know what the problem is. If you care to elaborate and provide some details on what exactly is not working I am willing to investigate further. Thanks.

**Comment by rstemmer** [comment]
My concern at this point is, when seeing a flood of messages in an error log, that I might some day figure out that all the data I added into the system is in some way corrupt.
So it is more a matter of trust in the functionality of the software, than having a particular issue.

I'm not deep enough in the code of this Project (not at all) and the PHP language to be able to assess how critical the logs are. :)
I just use this tool for my private time tracking. I've no resources to deeper investigate these issues. But as soon as I try to migrate to PHP8 again, I will look a bit closer into the logs.

kind regards,
Ralf

**Comment by anuko** [comment]
Most of php8 issues are design issues with the php dev team, specifically the way they change their mood every now and then and decide to reinvent things, breaking things along the way. What was perfectly okay before suddengly becomes an error or even a fatal error. Looking at fixes I have done so far to address these warnings: most of them are minor issues like undefined array index or variable (by design). There were a few useful fixes when we forgot about something. Also, a couple or so of php8 exceptions were addressed.

See how php8 changed error handling:

Reclassified engine warnings RFC

Lots of errors that previously only triggered warnings or notices, have been converted to proper errors. The following warnings were changed.

    Undefined variable: Error exception instead of notice
    Undefined array index: warning instead of notice
    Division by zero: DivisionByZeroError exception instead of warning
    Attempt to increment/decrement property '%s' of non-object: Error exception instead of warning
    Attempt to modify property '%s' of non-object: Error exception instead of warning
    Attempt to assign property '%s' of non-object: Error exception instead of warning
    Creating default object from empty value: Error exception instead of warning
    Trying to get property '%s' of non-object: warning instead of notice
    Undefined property: %s::$%s: warning instead of notice
    Cannot add element to the array as the next element is already occupied: Error exception instead of warning
    Cannot unset offset in a non-array variable: Error exception instead of warning
    Cannot use a scalar value as an array: Error exception instead of warning
    Only arrays and Traversables can be unpacked: TypeError exception instead of warning
    Invalid argument supplied for foreach(): TypeError exception instead of warning
    Illegal offset type: TypeError exception instead of warning
    Illegal offset type in isset or empty: TypeError exception instead of warning
    Illegal offset type in unset: TypeError exception instead of warning
    Array to string conversion: warning instead of notice
    Resource ID#%d used as offset, casting to integer (%d): warning instead of notice
    String offset cast occurred: warning instead of notice
    Uninitialized string offset: %d: warning instead of notice
    Cannot assign an empty string to a string offset: Error exception instead of warning
    Supplied resource is not a valid stream resource: TypeError exception instead of warning
