### ISSUE TITLE
Wrong decimal mark when activating project on user_edit.php

### ISSUE THREAD

**Issue by Adevade** [anuko/timetracker#14]
I have the comma `,` decimal mark selected in the settings for the current (and only) manager. 
But when I deactivate and reactivate the project it populates the `rate` field with a regular dot `.`.

I'm not very experienced with JavaScript, so unfortunately I don't feel comfortable providing a PR.

**Comment by anuko** [comment]
I fixed it (hopefully) in version 1.9.31.3536.

**Comment by Adevade** [comment]
Seems like it worked perfectly! Thank you! 

I'm just wondering, is it supposed to copy the value from `Default Hourly Rate` field? 
Because if that is empty when I toggle the project on/off the field for `Project Rate` does not change. Only when the default rate has a value.

**Comment by anuko** [comment]
Look at the getRate() function in WEB-INF/templates/user_edit.tpl

// getRate - returns a rate for the project. If rate was set for user previously we'll get this old rate
// if project time entries for user exists. Otherwise return user default rate.
function getRate(project_id) {
  var length = project_rates.length;
  for(var i = 0; i < length; i++) {
    if(project_rates[i][0] == project_id) {
      return project_rates[i][1];
    }
  }
  var default_rate = document.userForm.rate.value;
  return default_rate;
}

**Comment by anuko** [comment]
Closing as the issue appears resolved.
