### ISSUE TITLE
Whitespace changes

### ISSUE THREAD

**Issue by blomman9** [anuko/timetracker#31]
Please decide on tabs or spaces. Im getting merge conflicts due to whitespace. Also I'd be happy to keep the code tidy, once decided. Cheers!

**Comment by anuko** [comment]
Current vision is to have 2 spaces for each level of indentation, no tabs.

**Comment by blomman9** [comment]
OK Do you mind keeping this issue and close with a Pull request, one that can be tested and confirmed before continuing? 

Axed from [Angular Contributing Guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#rules):
**Type** Must be one of the following:

* feat: A new feature
* fix: A bug fix
* docs: Documentation only changes
* style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
* refactor: A code change that neither fixes a bug nor adds a feature
* perf: A code change that improves performance
* test: Adding missing or correcting existing tests
* chore: Changes to the build process or auxiliary tools and libraries such as documentation generation

Mind to tag this issue as `style` request?

Also may I add an issue to add testing to this project? I saw you where cleaning up the code.

**Comment by anuko** [comment]
Separate branch for white space looks like an overkill.

I think what we need is ongoing refactoring in very small iterations to simplify / clean up existing mess in code.

For the same reason I am against adding testing at this point, because I think it will most likely create additional problems rather than helping keeping code lean and simple. When the code base is clean enough, we may revisit automatic testing.
