### ISSUE TITLE
User roles and rights redesign

### ISSUE THREAD

**Issue by anuko** [anuko/timetracker#55]
Also discussed at https://www.anuko.com/forum/viewtopic.php?f=4&t=1833 this issue is to  to hear your thoughts on user roles and rights (or are they "permissions"?) redesign in Time Tracker.

Current problems:

1) Users are limited to one group, which is not enough for a mid-size organization.
2) User rights is currently a bit mask. It is obvious that we will run out of bits at some point after introducing more rights.

Currently suggested direction to solve both problems:

- Introduce a tree-like structure for organizations, with groups of 1 or more users possibly containing other groups in a parent-child relationship. Think about **tt_teams** table having **org_id,** **unit_id,** and **parent_unit_id** instead of just one id field,
- Have rights as an array of strings instead of bits in a number. For example:

CLIENT - when Clients plugin is enabled, a Client (which is external to a group) can be provided with a login to view own data such as reports, charts, and invoices.
**"view_own_data"** - view reports, charts, and invoices for self. The same right as for USER. What own data means: reports, charts, and invoices for this client. Note that clients do not have the "data_entry" right but can view what is entered into the system by other users and is associated with a specific client.

USER - a regular user in a group without any management rights. Primary function is data entry and viewing own data.
**"data_entry"** - enter time and expense records into Time Tracker.
**"view_own_data"** - view own reports and charts.

SUPERVISOR - a person who has a small set of management functions in a group. Has all of USER permissions plus the following.
**"on_behalf_data_entry"** - can enter data on behalf of lower roles.
**"view_group_data"** - can view data for lower roles.
**"override_punch_mode"** - can input any start and finish times for self and lower roles.
**"approve_timesheets"** - reserved for future approval workflow (not implemented at this point).

CO-MANAGER - a person with an extended set of management functions, who is helping a group manager with most of the work. Has all of SUPERVISOR permissions plus the following.
**"manage_users"** - can add, modify, delete, and assign roles to users with roles less than self.
**"manage_projects"** - full access to project management.
**"manage_tasks"** - full access to task management.
**"manage_clients"** - full access to client management.
**"manage_invoices"** - full access to invoice management.

MANAGER - a person with a full set of permissions to a group and the entire tree of its subgroups. Has all of CO-MANAGER permissions plus the following.
**"manage_group_settings"** - enable plugins, etc.
**"manage_roles"** - assign roles to users, create custom roles, etc,
**"export_data"** - export group and all subgroups data to an XML file.
**"manage_subgroups"** - add, modify, and delete subgroups. Essentially, it gives a capability to create subgroups and assume group manager role in there and all subgroups below.

CUSTOM - a customized role for situations when roles above do not suffice. Based on some already existing role to determine how **"manage_users"** works for it, if assigned. Has an arbitrary collection of permissions as set by group manager. Any number of custom roles can be defined.

ADMIN
**"administer_site"** - administer a site as a whole.

**Comment by it-world** [comment]
Hello,

it would be great if you implement these features. :)
What i also suggest is to implement a CSP Header.

Mit freundlichen Grüßen /
best regards
Markus Moravec


Am 19.02.2018 um 12:26 schrieb anuko <notifications@github.com<mailto:notifications@github.com>>:


Also discussed at https://www.anuko.com/forum/viewtopic.php?f=4&t=1833 this issue is to to hear your thoughts on user roles and rights (or are they "permissions"?) redesign in Time Tracker.

Current problems:

  1.  Users are limited to one group, which is not enough for a mid-size organization.
  2.  User rights is currently a bit mask. It is obvious that we will run out of bits at some point after introducing more rights.

Currently suggested direction to solve both problems:

  *   Introduce a tree-like structure for organizations, with groups of 1 or more users possibly containing other groups in a parent-child relationship. Think about tt_teams table having org_id, unit_id, and parent_unit_id instead of just one id field,
  *   Have rights as an array of strings instead of bits in a number. For example:

CLIENT - when Clients plugin is enabled, a Client (which is external to a group) can be provided with a login to view own data such as reports, charts, and invoices.

"view_own_data" - view reports, charts, and invoices for self. The same right as for USER. What own data means: reports, charts, and invoices for this client. Note that clients do not have the "data_entry" right but can view what is entered into the system by other users and is associated with a specific client.

USER - a regular user in a group without any management rights. Primary function is data entry and viewing own data.

"data_entry" - enter time and expense records into Time Tracker.
"view_own_data" - view own reports and charts.

SUPERVISOR - a person who has a small set of management functions in a group. Has all of USER permissions plus the following.

"on_behalf_data_entry" - can enter data on behalf of lower roles.
"view_group_data" - can view data for lower roles.
"override_punch_mode" - can input any start and finish times for self and lower roles.
"approve_timesheets" - reserved for future approval workflow (not implemented at this point).

CO-MANAGER - a person with an extended set of management functions, who is helping a group manager with most of the work. Has all of SUPERVISOR permissions plus the following.

"manage_users" - can add, modify, delete, and assign roles to users with roles less than self.
"manage_projects" - full access to project management.
"manage_tasks" - full access to task management.
"manage_clients" - full access to client management.
"manage_invoices" - full access to invoice management.

MANAGER - a person with a full set of permissions to a group and the entire tree of its subgroups. Has all of CO-MANAGER permissions plus the following.

"manage_group_settings" - enable plugins, etc.
"manage_roles" - assign roles to users, create custom roles, etc,
"export_data" - export group and all subgroups data to an XML file.
"manage_subgroups" - add, modify, and delete subgroups. Essentially, it gives a capability to create subgroups and assume group manager role in there and all subgroups below.

CUSTOM - a customized role for situations when roles above do not suffice. Based on some already existing role to determine how "manage_users" works for it, if assigned. Has an arbitrary collection of permissions as set by group manager. Any number of custom roles can be defined.

ADMIN ROLE
"administer_site" - administer a site as a whole.

**Comment by bonnedav** [comment]
How about a "view_own_tasks" permission that let's you view tasks for assigned projects?

**Comment by bonnedav** [comment]
And a similar "view_own_clients" permission to view clients assigned to the same projects as you are?

**Comment by anuko** [comment]
I agree with "view_own_tasks".

For clients, could you elaborate a bit on why it is needed?

As far as I understand, users access the Projects tab to see project descriptions, that may help them to decide which project to assign their time entries to, Projects and tasks do have descriptions, but clients don't. Do you suggest that we introduce client description field? Or explain what exactly a user sees on the Clients tab? What does it help them with?

Also, I think that we may have to re-design project to client assignments by introducing a client_id to tt_projects table so that each project is for one client only. Tasks may probably be left alone as there may be many generic activities (coding, testing, doing something) that fit into many projects.

**Comment by bonnedav** [comment]
I was thinking about the address field. The permission would not be default for users but could be granted if someone needs to see addresses for sending mail or something. Maybe show a contact email as well?

**Comment by anuko** [comment]
Good idea about contact email. I think we need to introduce the email field to tt_clients table and show it alongside with client address.

**Comment by anuko** [comment]
I added "view_own_tasks" and "view_own_clients" in this commit: https://github.com/anuko/timetracker/commit/e304b6c8564a6c3f2a3c6e68a0f5e9c7db817a65

A separate email field for clients will disrupt mobile view. I guess this has to wait until we have a better, responsive mobile template, so that the fields are displayed properly.

For now one could use the Address field to put it in, if needed.

**Comment by anuko** [comment]
Closing, as this thing is now done. May reopen if bugs are found.
