### ISSUE TITLE
Responsive Template based on Bootstrap 4 

### ISSUE THREAD

**Issue by anuko** [anuko/timetracker#58]
There are concerns about existing Time Tracker UI design, especially on small screens.

Current approach of having separate mobile code and page layout templates is not working well - there is duplication of code, and mobile section does require a lot of work to look good.

I am thinking about Bootstrap 4 based responsive design, no separate mobile section. Perhaps drop smarty templates altogether. I see a particular challenge with reports as there may be many columns there.

I plan to start working towards this goal after we do subgroups, which is a big task.

Feel free to suggest ideas and discuss if you feel like so.

New approach must be flexible enough to provide custom css and other templates, not necessarily responsive.

**Comment by amaurier** [comment]
I have rewritten some of the smarty templates with bootstrap 3 for an internal project at my company. Moving to twig would be a good idea.

**Comment by bkjproductions** [comment]
To me, the UI has its problems, sure, but the biggest problem is that there are not any consistent selectors.

For example, you have a clearly html-commented section "top menu for authorized user" but there is no ID for that section. Just create an ID for that table, call it "top_menu_authorized_user" perhaps, and then we have a handy selector we can do something with. 

Furthermore, add a class of "noprint" and an accompanying print style sheet and we can make it so that when printing, navigational elements and so forth aren't printed. (On my copy of self-hosted Time Tracker, I have gone in and added "noprint" to quite a number of areas, so that staff can easily print out a timesheet. Of course, this is doomed to failure because once I upgrade core Time Tracker code my changes will go away....)

Also there are a lot of places where width and so forth are specified in tables or table cells. Removing them would make it easier to be more responsive.

On small screens, if you are trying to show tabular information, maybe you have a way to turn on and off columns (user choice) and/or you could suggest to the user that tables have to be viewed in landscape orientation.

**Comment by anuko** [comment]
I added some table ids.

For printing, why don't we provide a different CSS for printing?

- link rel="stylesheet" media="screen and (min-width: 900px)" href="widescreen.css"
- link rel="stylesheet" media="screen and (max-width: 600px)" href="smallscreen.css"
- link rel="stylesheet" media="print" href="print.css"

If this will address the problem, feel free to suggest the content for print.css.

For other items we need to go on a case by case basis.

**Comment by anuko** [comment]
Closing, as current UI is already mobile friendly.
